from .bioscope import get_result_for_search_term_from_baiscope , get_subtitle_from_baiscope_by_id
from .zoomlk import get_result_for_search_term_from_zoomlk , get_subtitle_from_zoomlk_by_date , get_download_link_from_zoomlk
from .cineru import get_result_from_cineru , get_result_from_cineru_by_button_text
from .opensubtitles import get_result_from_opensubtitles , get_subtitle_by_file_id_from_opensubtitle

